console.log(Number(false))
console.log(Number(true))
console.log(Number(0))
console.log(Number(1))
console.log(Number("0"))
console.log(Number("000"))
console.log(Number("1"))
console.log(Number(NaN))
console.log(Number(Infinity))
console.log(Number(- Infinity))
console.log(Number("20"))
console.log(Number("Twenty"))
console.log(Number(null))
console.log(Number(undefined))

console.log(String(false))
console.log(String(true))
console.log(String(0))
console.log(String(1))
console.log(String("0"))
console.log(String("000"))
console.log(String("1"))
console.log(String(NaN))
console.log(String(Infinity))
console.log(String(- Infinity))
console.log(String("20"))
console.log(String("Twenty"))
console.log(String(null))
console.log(String(undefined))


console.log(Boolean(false))
console.log(Boolean(true))
console.log(Boolean(0))
console.log(Boolean(1))
console.log(Boolean("0"))
console.log(Boolean("000"))
console.log(Boolean("1"))
console.log(Boolean(NaN))
console.log(Boolean(Infinity))
console.log(Boolean(- Infinity))
console.log(Boolean("20"))
console.log(Boolean("Twenty"))
console.log(Boolean(null))
console.log(Boolean(undefined))